language: python

env:
  - PYTHON_VERSION=3.6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libopenmpi-dev
      - openmpi-bin

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
    - install_prefix=~
    - conda create -n testenv --yes pip python=${PYTHON_VERSION}
    - source activate testenv
    - conda install --yes scipy numpy matplotlib
    - pip install flake8 pytest pytest-cov
    - pip install mne psutil mpi4py joblib
    - pip install coverage coveralls
    - |
      git clone https://github.com/neuronsimulator/nrn
      cd nrn
      ./build.sh
      ./configure --with-nrnpython=python3 --without-iv --prefix=${install_prefix} \
        --with-paranrn --disable-rx3d --without-nrnoc-x11 --with-mpi
      make -j4
      make install -j4
      cd src/nrnpython/
      python3 setup.py install
    - |
      cd $TRAVIS_BUILD_DIR
      export PATH=$PATH:${install_prefix}/x86_64/bin
      make
      python setup.py develop
script:
    - flake8 --count hnn_core
    - py.test --cov=hnn_core hnn_core/tests/
after_success:
    - bash <(curl -s https://codecov.io/bash)
