[build-system]
requires = ["setuptools>=40.8.0", "NEURON >=7.7; platform_system != 'Windows'"]
build-backend = "setuptools.build_meta"

[project]
name = "hnn-core"
version = "0.1.1"
dependencies = [
    "numpy >= 1.14",
    "matplotlib >= 3.5.3",
    "scipy",
    "NEURON >= 7.7; sys_platform != 'win32'",
    "h5io",
]
authors = [
    { name="Stephanie Jones", email="stephanie_jones@brown.edu" },
    { name="Mainak Jas", email="mainakjas@gmail.com" },
    { name="Nicholas Tolley", email="nicholas_tolley@brown.edu" },
    { name="Ryan Thorpe", email="ryan_thorpe@brown.edu" },
]
maintainers = [
    {name="George Dang", email="george_dang@brown.edu"},
    {name="Dylan Daniels", email="dylan_s_daniels@brown.edu"},

]
description = "Tools for biophysical simulation of a cortical column using Neuron"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: BSD (3-clause)",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Developers",
    "Topic :: Software Development",
    "Topic :: Scientific/Engineering",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX",
    "Operating System :: Unix",
    "Operating System :: MacOS",
]

[project.optional-dependencies]
opt = ['scikit-learn']
test = ['flake8', 'pytest', 'pytest-cov']
docs = [
    'mne', 'nibabel', 'pooch', 'tdqm', 'sphinx',
    'sphinx-gallery', 'sphinx_bootstrap_theme', 'sphinx-copybutton',
    'pillow', 'numpydoc',
]
parallel = ['joblib', 'psutil', 'mpi4py']
gui = ['ipywidgets>=8.0.0', 'ipykernel', 'ipympl', 'voila']
dev = ["hnn-core[opt,test,docs,parallel,gui]"]

[project.urls]
"Homepage" = "https://jonescompneurolab.github.io/hnn-core"
"Source Code" = "http://github.com/jonescompneurolab/hnn-core"

[tool.codespell]
skip = '.git,*.pdf,*.svg'
check-hidden = true
# in jupyter notebooks - images and also some embedded outputs
ignore-regex = '^\s*"image/\S+": ".*|.*%22%3A%20.*'
ignore-words-list = 'tha,nam,sherif,dout'
