name: Unit tests

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

envs:
    PYTHONPATH: C:\nrn_test\lib\python
    NEURONHOME: C:\nrn_test

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.7, 3.8]

    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install Neuron on Windows separately
        shell: cmd
        run: |
          powershell -command "gh release download --repo https://github.com/neuronsimulator/nrn --pattern '*.exe' --output nrn-setup.exe"
          start /b /wait .\nrn-setup.exe /S /D=C:\nrn_test
          "C:\nrn_test\bin" >> $env:GITHUB_PATH
          python -c "import neuron"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies and HNN
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest pytest-cov
          pip install psutil joblib
          pip install --verbose .[gui]
      - name: Test with pytest
        shell: cmd
        run: |
          python -m pytest .  --cov=hnn_core hnn_core/tests/ --cov-report=xml
