name: Unit test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
    PYTHONPATH: C:\nrn_test\lib\python
    NEURONHOME: C:\nrn_test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.9, 3.11, 3.13]

    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}

      - name: Install Neuron on Windows separately
        shell: cmd
        run: |
          powershell -command "gh release download 8.2.7 --repo https://github.com/neuronsimulator/nrn --pattern '*.exe' --output nrn-setup.exe"
          start /b /wait .\nrn-setup.exe /S /D=C:\nrn_test
          powershell -command "'C:\nrn_test\bin' >> $env:GITHUB_PATH"
          python -c "import neuron"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install HNN-Core with minimal dependencies and test
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install --verbose .
          python -c "from hnn_core import jones_2009_model, simulate_dipole; simulate_dipole(jones_2009_model(), tstop=20); print('--> SUCCESS: The test worked!')"

      - name: Clean minimal dependencies install
        shell: cmd
        run: |
          pip uninstall --yes hnn_core
          rmdir /s /q build

      - name: Install HNN-Core with full dependencies
        shell: cmd
        run: |
          pip install --verbose .[opt,parallel,test,gui]

      - name: Check ruff formatting
        shell: cmd
        run: |
          python -m ruff format hnn_core --check

      - name: Lint with ruff
        shell: cmd
        run: |
          python -m ruff check hnn_core

      - name: Test non-MPI, embarrassingly parallel tests with pytest
        shell: cmd
        run: |
          python -m pytest ./hnn_core/tests/ -m "not uses_mpi" -n auto

      - name: Test MPI-using parallel tests with pytest
        shell: cmd
        run: |
          python -m pytest ./hnn_core/tests/ -m "uses_mpi"
