name: Unit test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

env:
    PYTHONPATH: C:\nrn_test\lib\python
    NEURONHOME: C:\nrn_test

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [3.8, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: test
          python-version: ${{ matrix.python-version }}
      - name: Install Neuron on Windows separately
        shell: cmd
        run: |
          powershell -command "gh release download --repo https://github.com/neuronsimulator/nrn --pattern '*.exe' --output nrn-setup.exe"
          start /b /wait .\nrn-setup.exe /S /D=C:\nrn_test
          powershell -command "'C:\nrn_test\bin' >> $env:GITHUB_PATH"
          python -c "import neuron"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies and HNN
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install --verbose .[opt,parallel,test,gui]
      - name: Test with pytest
        shell: cmd
        run: |
          python -m pytest ./hnn_core/tests/
